version: '3'

services:

  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD

  node:
    image: node
    #command: sleep 99999
    command: sh -c 'cd /src; npm i; npm run populate; npm run sql'
    volumes:
      - ./node:/src
    environment:
      - PGHOST=pg
      - PGUSER=postgres
      - PGDATABASE=node
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=5432
